dslearning/urls.py
from django.urls import include, path

from website.views import vadmins, vstudents, vteachers,vanonymous

urlpatterns = [
    path('', include('website.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', vstudents.StudentSignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', vstudents.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', vadmins.TeacherSignUpView.as_view(), name='teacher_signup'),
]

website/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from .views import vanonymous, vstudents, vteachers,vadmins

urlpatterns = [
    #Accès public
    
    path('',vanonymous.accueil, name='accueil'),
    path('login/', auth_views.LoginView.as_view()),
        path('contact/',vanonymous.contact, name='contact'),
        path('about/',vanonymous.Apropos, name='Apropos'),
        path('inscrit/',vstudents.StudentSignUpView.as_view(), name='inscription'),    
        path('training/',vanonymous.training, name='training'),
        path('forgetPw/',vanonymous.forgetPw, name='forgetPw'),
        path('profil/',vanonymous.profil, name='profil'),
    
    
    #Fonctions teacher
    path('teachers/', include(([
        path('', vteachers.teacher_home, name='teahome'),
        path('course/list/',vteachers.CoursesListView.as_view(), name='course_list'),
        path('course/listj/',vteachers.crs_list, name='crs_listj'),

        path('chapters/<int:pk>/', vteachers.fadd_chapters, name='chapters_change_list'),
        path('chapters/add/<int:pk>/', vteachers.addchapter, name='chap'),

        path('quizes', vteachers.QuizListView.as_view(), name='quiz_change_list'),

        path('quiz/add/', vteachers.QuizCreateView.as_view(), name='quiz_add'),
        path('quiz/<int:pk>/', vteachers.QuizUpdateView.as_view(), name='quiz_change'),
        path('quiz/<int:pk>/delete/', vteachers.QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/results/', vteachers.QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:pk>/question/add/', vteachers.question_add, name='question_add'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/', vteachers.question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', vteachers.QuestionDeleteView.as_view(), name='question_delete'),

    ], 'classroom'), namespace='teachers')),
    


    #Fonctions student
    path('students/', include(([
        

        path('',vstudents.student_home,name='student_home'),        
        path('allcourses/',vstudents.admin_home,name='all_courses'),
        path('mycourses/',vstudents.crs_list,name='mycourses'),

        path('q',vstudents.QuizListView.as_view(), name='quiz_list'),
        path('taken/',vstudents.TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>/',vstudents.take_quiz, name='take_quiz'),
        path('subscribe/<int:pk>/',vstudents.subscribe, name='subscribe'),

        path('chapter/<int:cle>',vstudents.ListChapadmin, name='Chapter'),
        path('chapter/details/<int:num>',vstudents.DetailsChapAdmin, name='Chapter'),
       

    ], 'website'), namespace='students')),
    
    
    #Fonctions admin
    path('admin/', include(([
        path('',vadmins.admin_home,name='admin_home'),

        path('category/list/',vadmins.CategoryListView.as_view(), name='categories_list'),
        path('category/listj/',vadmins.categ_list, name='cat_listj'),
        path('category/add/',vadmins.CategoryCreateView.as_view(), name='categories_add'),        
        path('category/<int:pk>/',vadmins.CategoryUpdate.as_view(), name='categories_edit'),

        path('course/add/',vadmins.CourseCreateView.as_view(), name='course_add'),
        path('course/list/',vadmins.CoursesListView.as_view(), name='course_list'),
        path('course/listj/',vadmins.crs_list, name='crs_listj'),
        path('course/<int:pk>/',vadmins.CourseUpdate.as_view(), name='course_edit'),


        path('teacher/list/',vadmins.TeachersListView.as_view(), name='tch_list'),
        path('teacher/listj/',vadmins.tech_list, name='tch_listj'),
        path('teacher/add/',vadmins.TeacherSignUpView.as_view(), name='tch_add'),
        path('teacher/<int:pk>/',vadmins.TeacherUpdate.as_view(), name='tch_edit'),
        path('teacher/<int:pk>/delete',vadmins.tdelete_teacher, name='tch_delete'),


    ], 'website'), namespace='admins')), 

    
]

website/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, 'base.html')

website/views/vadmins.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,UpdateView)
from ..decorators import teacher_required,admin_required
from ..forms import BaseAnswerInlineFormSet, QuestionForm, TeacherSignUpForm,CategoryCreation,CourseCreation, UserUpdateForm
from ..models import Answer, Question, Quiz, User,Category,Course,Teacher
from django.core import serializers
import json
from django.http import JsonResponse


#Home
def admin_home(request):
    return render(request, 'wbtemp/t_admins/admin_home.html')
#####################################################################

'''________________________Teachers#_____________________________'''
#_____________________________Add_____________________________#

class TeacherSignUpView(CreateView):
    model = User
    form_class = TeacherSignUpForm
    template_name = 'wbtemp/t_admins/teacher_add.html'
    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'teacher'
        return super().get_context_data(**kwargs)
    def form_valid(self, form):
        user = form.save()
        return redirect('admins:tch_list')
#_____________________________get_____________________________#

def tech_list(request):
    data=[]
    for usr in User.objects.filter(is_teacher=True):
        user={'user_id':usr.user_id,'first_name':usr.first_name, 'last_name':usr.last_name,'username':usr.username,'email':usr.email,'last_login':usr.last_login,'date_joined':usr.date_joined}
        data.append(user)
    return JsonResponse({"data":data})
#_____________________________delete_____________________________#

def tdelete_teacher(request,pk):
    try:
        Teacher.objects.filter(user_id=int(pk)).delete()
        User.objects.filter(user_id=int(pk)).delete()
        return JsonResponse({"status": "ok"})
    except Exception as e:
        return JsonResponse({"status": "not ok:\n"+str(e)})        
#_____________________________view_________________________________#    
class TeachersListView(ListView):
    model = Teacher
    ordering = ('first_name', )
    context_object_name = 'teachers'
    template_name = 'wbtemp/t_admins/teacher_list.html'

    def get_queryset(self):
        # Retreive all slot id for the customer with id = 1
        queryset = User.objects.all().filter(is_teacher=True)
        return queryset
#_____________________________Update__________________________________#

class TeacherUpdate(UpdateView):
        model = User
        fields = ('first_name', 'last_name','username','email',)  
        context_object_name = 'teacher'
        template_name = 'wbtemp/t_admins/teacher_edit.html'
        success_url = '/admin/teacher/list'
        

        def get_context_data(self, **kwargs):
            return super().get_context_data(**kwargs)
        def get_queryset(self):
            return super().get_queryset()


'''_____________________________Categories_____________________________'''
#_____________________________Add_____________________________________#

class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryCreation
    template_name = 'wbtemp/t_admins/category_add.html'
    def get_context_data(self):
        return super().get_context_data()
    def form_valid(self, form):
        category = form.save()
        return redirect('admins:categories_list')
#_____________________________List_____________________________________#

class CategoryListView(ListView):
    model = Category
    ordering = ('name', )
    context_object_name = 'categories'
    template_name = 'wbtemp/t_admins/category_list.html'

    def get_queryset(self):
        queryset = Category.objects.all()
        return queryset
#_____________________________get_____________________________#

def categ_list(request):
    data=[]
    for usr in Category.objects.all():
        cat={'id':usr.id,'name':usr.name, 'description':usr.description}
        data.append(cat)
    return JsonResponse({"data":data})
#_____________________________Update__________________________________#

class CategoryUpdate(UpdateView):
        model = Category
        fields = ('name', 'description',)  
        context_object_name = 'category'
        template_name = 'wbtemp/t_admins/categorie_edit.html'
        success_url = '/admin/category/list'

        def get_context_data(self, **kwargs):
            return super().get_context_data(**kwargs)
        def get_queryset(self):
            return super().get_queryset() 

'''_____________________________Courses_____________________________'''
class CoursesListView(ListView):
    model = Course
    ordering = ('name', )
    context_object_name = 'courses'
    template_name = 'wbtemp/t_admins/course_list.html'

    def get_queryset(self):
        queryset = Course.objects.all()
        return queryset

class CourseCreateView(CreateView):
    model = Course
    form_class = CourseCreation
    template_name = 'wbtemp/t_admins/course_add_form.html'

    def form_valid(self, form):
        quiz = form.save(commit=False)
        quiz.save()
        messages.success(self.request, 'The course was created with success')
        return redirect('admins:course_list')
#_____________________________get_____________________________#

def crs_list(request):
    data=[]
    for usr in Course.objects.all():
        cat={'id':usr.id,'name':usr.name, 'description':usr.description}
        data.append(cat)
    return JsonResponse({"data":data})
#_____________________________Update__________________________________#

class CourseUpdate(UpdateView):
        model = Course
        fields = ('name', 'description',)  
        context_object_name = 'category'
        template_name = 'wbtemp/t_admins/course_edit.html'
        success_url = '/admin/course/list'

        def get_context_data(self, **kwargs):
            return super().get_context_data(**kwargs)
        def get_queryset(self):
            return super().get_queryset() 

website/views/vanonymous.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView


def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return render(request, 'wbtemp/teachers/home.html')
        elif request.user.is_admin:
            return render(request, 'wbtemp/admins/home.html')
        else:
            return render(request, 'wbtemp/students/home.html')
    return render(request, 'wbtemp/home.html')

def contact(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return render(request, 'wbtemp/teachers/home.html')
        elif request.user.is_admin:
            return render(request, 'wbtemp/admins/home.html')
        else:
            return render(request, 'wbtemp/students/home.html')
    return render(request, 'wbtemp/contact.html')

def courses(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return render(request, 'wbtemp/teachers/home.html')
        elif request.user.is_admin:
            return render(request, 'wbtemp/admins/home.html')
        else:
            return render(request, 'wbtemp/students/home.html')
    return render(request, 'wbtemp/courses.html')

def teachers(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return render(request, 'wbtemp/teachers/home.html')
        elif request.user.is_admin:
            return render(request, 'wbtemp/admins/home.html')
        else:
            return render(request, 'wbtemp/students/home.html')
    return render(request, 'wbtemp/teachers.html')

def fiche_teacher(request,pk):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return render(request, 'wbtemp/teachers/home.html')
        elif request.user.is_admin:
            return render(request, 'wbtemp/admins/home.html')
        else:
            return render(request, 'wbtemp/students/home.html')
    return render(request, 'wbtemp/teachers.html')
from django.shortcuts import render
from django.http import HttpResponse


def accueil(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return render(request, 'wbtemp/t_teachers/teacher_home.html')
        elif request.user.is_admin:
            return render(request, 'wbtemp/t_admins/admin_home.html')
        else:
            return render(request, 'wbtemp/t_students/student_home.html')
    return render(request, 'wbtemp/t_anonymous/accueil.html')
    


def contact(request):
    return render(request, "wbtemp/t_anonymous/Contact.html")


def Apropos(request):
    return render(request, "wbtemp/t_anonymous/Apropos.html")


def inscription(request):
    return render(request, "wbtemp/t_anonymous/inscription.html")


def login(request):
    return render(request, "wbtemp/t_anonymous/login.html")


def training(request):
    return render(request, "wbtemp/t_anonymous/Training.html")


def forgetPw(request):
    return render(request, "wbtemp/t_anonymous/oblieMDP.html")


def profil(request):
    return render(request, "wbtemp/t_anonymous/ProfilUser.html")

website/templates/wbtemp/t_students/_header.html
<h2>Quizzes</h2>
<p class="text-muted">
  Subjects:{% for subject in user.student.interests.all %} {{ subject.get_html_badge }}{% endfor %}
  <a href="{% url 'students:student_interests' %}"><small>(update interests)</small></a>
</p>

<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <a class="nav-link{% if active == 'new' %} active{% endif %}" href="{% url 'students:quiz_list' %}">New</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if active == 'taken' %} active{% endif %}" href="{% url 'students:taken_quiz_list' %}">Taken</a>
  </li>
</ul>

website/templates/wbtemp/t_students/base copy.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>DS Learning</title>


  <link href="{%  static  'css/bootstrap.min.css'  %}" rel="stylesheet">
  <link href="{% static 'css/animate.min.css' %}" rel="stylesheet"> 
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/lightbox.css' %}" rel="stylesheet">
  <link href="{% static 'css/main.css' %}" rel="stylesheet">
  <link id="css-preset" href="{% static 'css/presets/preset1.css' %}" rel="stylesheet">
  <link href="{% static 'css/responsive.css'%}" rel="stylesheet">

  <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
  <![endif]-->
  
   
  <style>
    .dropdown-menu>li>a {
    padding: 6px 40px;
  }
     .navbar .dropdown-menu {
    background-color: #028fcc;
  }
  .navbar-nav > .active > a { 
      background-color: #028fcc ; 
  }
  
  /* and this styles the dropdwon trigger link, when open */
  .navbar .dropdown.show a { 
    background-color: #028fcc;
  }
/* #cc {
  position:absolute;
  top:50%;
   left:50%;
   width:300px; 
   height:200px;
   margin-left:-150px; 
   margin-top:-100px; 
  
  } */

    </style>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

</head><!--/head-->

<body>

  <!--.preloader-->
  <div class="preloader"> <i class="fa fa-circle-o-notch fa-spin"></i></div>
  <!--/.preloader-->

  <header id="home">
    
    <div class="main-nav">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
            <h1><img class="img-responsive" src="{%  static './images/log1.png' %}" alt="log" width="210" height="210"></h1>
          </a>                    
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">                 
            
            <li class="scroll "><a href="">All Courses</a></li>          
            <li class="scroll "><a href="">My Courses</a></li>
            <li class="scroll"><a href="">Logout</a></li>
                 
          </ul>
        </div>
      </div>
    </div><!--/#main-nav-->
  </header><!--/#home-->


    {% block content %}

      <div class="container">
        <div class="card">
        
            <div class="card-body">
            
               <div class="row">
                
            <div class="col-6">
              <h3 class="mb-3"> {{cat.name}} </h3>
            </div>
            
            <!--<div class="col-3 text-left" style="text-align: right;">
              <a class="btn btn-primary mb-3 mr-1" href="#home-slider1" role="button" data-slide="prev">
                <i class="fa fa-arrow-left"></i>
              </a>
              <a class="btn btn-primary mb-3 " href="#home-slider1" role="button" data-slide="next">
                <i class="fa fa-arrow-right"></i>
              </a>
            </div>-->
            <div class="col-12">
              <div id="home-slider1" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                 
                  <div class="item active">
                   
                    <div class="row">
                      {% for cours in courses %}
                      <div class="col-md-4 mb-3">
    
                        <div class="card">
                          <img class="img-fluid" alt="100%x280" src="{% static 'images/slider/1.jpg' %}" width="280"
                            height="180"> <p class="card-text">{{cours.description}}</p>
                          <div class="card-block">
                            <h4 class="card-title">{{cours.name}}</h4>
                            
                            
                              <button class="btn btn-default swap">
                                <span class="glyphicon glyphicon-heart-empty"></span>
                            </button>
                            <a href="Chapter/{{cours.id}}" class="btn btn-primary">View chapters</a>
                          </div>
    
                        </div>
                      </div>
                      {% empty %}
                      <p>no courses</p>
                     
                  </div>
    
    
                  </div>
                </div>
    
               <!---- <a class="left-control" href="#home-slider1" data-slide="prev"><i class="fa fa-angle-left"></i></a>
                <a class="right-control" href="#home-slider1" data-slide="next"><i class="fa fa-angle-right"></i></a>-->
              </div>
            </div>
            {% endfor %}
          </div>
            </div>
          </div>
      </div>
    {% endblock %}   
  




  <footer id="footer">
    
    <div class="footer-bottom">
      <div class="container">
        <div class="row">
            <div class="social-icons">
                <ul>
                  <li><a class="envelope" href="#"><i class="fa fa-envelope"></i></a></li>
                  <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li> 
                  <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
                  <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                  <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
                  <li><a class="tumblr" href="#"><i class="fa fa-tumblr-square"></i></a></li>
                </ul>
              </div>
          
        </div>
      </div>
    </div>
  </footer>

  <script type="text/javascript" src="{%  static 'js/jquery.js' %}"></script>
  <script type="text/javascript" src="{%  static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src=" http://maps.google.com/maps/api/js?sensor=true"></script>
  <script type="text/javascript" src="{%  static 'js/jquery.inview.min.js' %}"></script>
  <script type="text/javascript" src="{%  static 'js/wow.min.js' %}"></script>
  <script type="text/javascript" src="{%  static 'js/mousescroll.js' %}"></script>
  <script type="text/javascript" src="{%  static 'js/smoothscroll.js' %}"></script>
  <script type="text/javascript" src="{%  static 'js/jquery.countTo.js' %}"></script>
  <script type="text/javascript" src="{%  static 'js/lightbox.min.js' %}"></script>
  <script type="text/javascript" src="{%  static 'js/main.js' %}"></script>

  </body>
  </html>

website/templates/wbtemp/t_students/course_list.html
{% extends 'wbtemp/t_students/base.html' %}
{% load static %}
   {% block content %}
   <div class="container">

  {% for c in cat %}
   <div class="card">
       <div class="card-header" >
        <h3 class="mb-3"> {{c.category}} </h3>
       </div>
    <div class="card-body">
      <div class="row">
    <div class="col-12">
      <div id="home-slider1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
         
          <div class="item active">
           
            <div class="row">
              {% for cours in c.courses %}
              <div class="col-md-4 mb-3">

                <div class="card">
                  <img class="img-fluid" alt="100%x280" src="{% static 'images/slider/1.jpg' %}" width="280"
                    height="180"> <p class="card-text">{{cours.description}}</p>
                  <div class="card-block">
                    <h4 class="card-title">{{cours.name}}</h4>
                    
                    
                      <button class="btn btn-default swap" value="{{cours.id}}">
                        <span class="glyphicon glyphicon-heart-empty"></span>
                    </button>
                    <!-- <a href="Chapter/{{cours.id}}" class="btn btn-primary">View chapters</a> -->
                  </div>

                </div>
              </div>
              {% endfor %}
           
             
          </div>


          </div>
        </div>

       <!---- <a class="left-control" href="#home-slider1" data-slide="prev"><i class="fa fa-angle-left"></i></a>
        <a class="right-control" href="#home-slider1" data-slide="next"><i class="fa fa-angle-right"></i></a>-->
      </div>
    </div>
  
  </div>
    </div>
  </div>
  {% empty %}
  <p>No courses</p>
  {% endfor %}
</div>
{% endblock %}

website/templates/wbtemp/t_students/details_chap.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>DS Learning</title>


  <link href="{%  static  'css/bootstrap.min.css'  %}" rel="stylesheet">
  <link href="{% static 'css/animate.min.css' %}" rel="stylesheet"> 
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/lightbox.css' %}" rel="stylesheet">
  <link href="{% static 'css/main.css' %}" rel="stylesheet">
  <link id="css-preset" href="{% static 'css/presets/preset1.css' %}" rel="stylesheet">
  <link href="{% static 'css/responsive.css'%}" rel="stylesheet">

  <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
  <![endif]-->
  
   
  <style>
    .dropdown-menu>li>a {
    padding: 6px 40px;
  }
     .navbar .dropdown-menu {
    background-color: #028fcc;
  }
  .navbar-nav > .active > a { 
      background-color: #028fcc ; 
  }
  
  /* and this styles the dropdwon trigger link, when open */
  .navbar .dropdown.show a { 
    background-color: #028fcc;
  }
/* #cc {
  position:absolute;
  top:50%;
   left:50%;
   width:300px; 
   height:200px;
   margin-left:-150px; 
   margin-top:-100px; 
  
  } */

    </style>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

</head><!--/head-->

<body>

  <!--.preloader-->
  <div class="preloader"> <i class="fa fa-circle-o-notch fa-spin"></i></div>
  <!--/.preloader-->

  <header id="home">
    
    <div class="main-nav">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
            <h1><img class="img-responsive" src="{%  static './images/log1.png' %}" alt="log" width="210" height="210"></h1>
          </a>                    
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">                 
            
            <li class="scroll "><a href="">All Courses</a></li>          
            <li class="scroll "><a href="">My Courses</a></li>
            <li class="scroll"><a href="">Logout</a></li>
                 
          </ul>
        </div>
      </div>
    </div><!--/#main-nav-->
  </header><!--/#home-->


{% block content %}
 <div class="card">
    
    {% for chapitre in khra %}
    <h1>chapter : {{chapitre.num}} &nbsp; {{chapitre.name}}<b></b></h1>
    
    <p> {{chapitre.description}}</p>
   
    {% endfor %}

  </div>
{% endblock %}
<script type="text/javascript" src="{%  static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{%  static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src=" http://maps.google.com/maps/api/js?sensor=true"></script>
<script type="text/javascript" src="{%  static 'js/jquery.inview.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'js/wow.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'js/mousescroll.js' %}"></script>
<script type="text/javascript" src="{%  static 'js/smoothscroll.js' %}"></script>
<script type="text/javascript" src="{%  static 'js/jquery.countTo.js' %}"></script>
<script type="text/javascript" src="{%  static 'js/lightbox.min.js' %}"></script>
<script type="text/javascript" src="{%  static 'js/main.js' %}"></script>

</body>
</html>

website/templates/wbtemp/t_students/interests_form.html
{% extends 'wbtemp/t_admins/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2 class="mb-3">Update your interests</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'students:quiz_list' %}" class="btn btn-outline-secondary">Nevermind</a>
  </form>
{% endblock %}

website/templates/wbtemp/t_students/quiz_list.html
{% extends 'wbtemp/t_students/base.html' %}

{% block content %}

  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Quiz</th>
          <th>Subject</th>
          <th>Length</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in quizzes %}
          <tr>
            <td class="align-middle">{{ quiz.name }}</td>
            <td class="align-middle">{{ quiz.subject.get_html_badge }}</td>
            <td class="align-middle">{{ quiz.questions_count }} questions</td>
            <td class="text-right">
              <a href="{% url 'students:take_quiz' quiz.pk %}" class="btn btn-primary">Start quiz</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="4">No quiz matching your interests right now.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

website/templates/wbtemp/t_students/student_home.html
{% extends 'wbtemp/t_students/base.html' %}